const GENERATION_TYPES = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
}

const DRAGON_TYPES = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
}

const ACCOUNT_TYPES = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
}

const ACCOUNT_DRAGONS_TYPES = {
    FETCH: 'ACCOUNT_DRAGONS_FETCH',
    FETCH_ERROR: 'ACCOUNT_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_DRAGONS_FETCH_SUCCESS'
}

const ACCOUNT_INFO_TYPES = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
}

const PUBLIC_DRAGONS_TYPES = {
    FETCH: 'PUBLIC_DRAGONS_FETCH',
    FETCH_ERROR: 'PUBLIC_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_DRAGONS_FETCH_SUCCESS'
}

export { 
     DRAGON_TYPES, 
     GENERATION_TYPES, 
     ACCOUNT_TYPES,
     ACCOUNT_DRAGONS_TYPES,
     ACCOUNT_INFO_TYPES,
     PUBLIC_DRAGONS_TYPES
     };